### ISSUE TITLE
Counting grids

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#100]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

I have added a count to domain  - 

    ddata->count_single_step

which counts the number of individual grid advances.   However, I still need a way to accumulate the totals across procs.    Does SC  have any thing like the timer accumulatators for integer data?   

I assume that what we want is 

    total number of grids (or equivalently, grid cells) advanced over all procs) / wall time

Is that right?

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/100

**Comment by cburstedde** [comment]
Is the current functionality in stats sufficient, or do we need something extra?

**Comment by donnaaboise** [comment]
The current functionality has been sufficient. In fact, I probably went overboard in producing timing results, i.e. difference between arithemetic and geometric mean.
