### ISSUE TITLE
Indirect ghost exchange at corners?

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#102]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

Can corners be exchanged by present indirect ghost exchange algorithm?  That is if two ghost patches are corner adjacent, they may need to exchange data.   This will in general be needed if an interpolation stencil requires corners.    The current interpolation stencils do not require corners, so we are good for now.  But eventually, this capability would be needed. 

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/102

**Comment by cburstedde** [comment]
Would not be too hard to do when we need it.

**Comment by cburstedde** [comment]
How urgent is this feature?

While at it, we may want to think about indirect edge neighbors in 3D. What features will we need there exactly?

Related, if we're thinking the minimal 3D example will use face-only neighbor contacts, is the indirect exchange needed at all? Currently it is not being translated to 3D, but I could change it (will have to eventually anyway).
