### ISSUE TITLE
Minimal timer output?

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#112]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

It would be nice to have the option of limiting the timing output to a few key (exclusive) timers : 

    Walltime 
    Advance
    Ghost fill
    Ghost comm

Or even, just 

    AMR Tasks
    Communication 
    Advance 
    Walltime  

Something like `report-timing=<N>`, where N=0 is no reporting (already implemented), N=1 is minimal and N=2 more input, etc.   

Right now, the timers are really long, and may not be of interest to the typical user.

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/112

**Comment by cburstedde** [comment]
Check out the enhanced API in libsc's sc_statistics.h, branch feature-stats-prio. Comments?

**Comment by donnaaboise** [comment]
We now have this capability.
