### ISSUE TITLE
timing output bug?

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#117]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

Something wrong with the timing output - and this was a serial run ..

```
[libsc]    Maximum attained at rank     0: 11.7025
[libsc] Statistics for GHOSTPATCH_COMM
[libsc]    Global number of values:     1
[libsc]    Mean value (std. dev.):        [libsc   Minimum attained at rank     0: 1
[libsc   Maximum attained at rank     0: 1
[libscStatistics for GRIDS_LOCAL_BOUNDARY
[libsc   Global number of values:     1
[libsc   Mean value (std. dev.):         0 (0)
[libsc   Minimum attained at rank     0: 0
[libsc   Maximum attained at rank     0: 0
[libscStatistics for GRIDS_INTERIOR
[libsc   Global number of values:     1
[libsc   Mean value (std. dev.):         1 (0 = 0%)
[libsc   Minimum attained at rank     0: 1
[libsc   Maximum attained at rank     0: 1
[libscStatistics for GRIDS_LOCAL_BOUNDARY_RATIO
[libsc   Global number of values:     1
[libsc   Mean value (std. dev.):         1 (0 = 0%)
[libsc   Minimum attained at rank     0: 1
[libsc   Maximum attained at rank     0: 1

```

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/117

**Comment by cburstedde** [comment]
Weird. Is this reproducible?

**Comment by donnaaboise** [comment]
It happens fairly rarely, and mostly on supercomputers.  I'll try to keep track of when it happens.  Of course, it would be less of an issue if I weren't try to parse the output file, but instead just used the summary statistics available at the end of the output.

**Comment by cburstedde** [comment]
> It happens fairly rarely, and mostly on supercomputers.  I'll try to keep track of when it happens.  Of course, it would be less of an issue if I weren't try to parse the output file, but instead just used the summary statistics available at the end of the output.

It is very much advised to process the summary line.  The multi-line output is
really just for humans and not as reliable in parallel.
