### ISSUE TITLE
Problem with normal_match in parallel

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#130]
I have the parallel implementation working for the conservative fix, but am running into assertion errors in the `normal_match` routine.  If I don't call this routine, the code runs on multiple processors, and maintains conservation.  But including the `normal_match` call causes an assertion failure at this line:

```
FCLAW_ASSERT (0 <= patchno && patchno < block->num_patches);
```

**Comment by donnaaboise** [comment]
Problem is in my code that is calling this routine - See #129.

**Comment by cburstedde** [comment]
Some routines in forestclaw2d.h are legal to allow from ghost cells, others are not.
I need to improve documentation and put in more assertions.

**Comment by cburstedde** [comment]
The convention is that routines in forestclaw2d.h taking blockno, patchno are legal for local patches only.
Whenever fclaw2d_patch_t * is passed (i.e., to the transforms), ghosts are fine, too.
The iterator callbacks are called for local patches by construction.
