### ISSUE TITLE
Including .ini, .m files, .py in distribution. 

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#135]
Add any extra files to the EXTRA_DIST flag, i.e.  in the swirl example, we have added : 

```
EXTRA_DIST += \
	applications/clawpack/advection/2d/swirl/fclaw_options.ini \
	applications/clawpack/advection/2d/swirl/regression.ini \
	applications/clawpack/advection/2d/swirl/afterframe.m \
	applications/clawpack/advection/2d/swirl/setplot2.m \
	applications/clawpack/advection/2d/swirl/swirl.ipynb \
	applications/clawpack/advection/2d/swirl/make_plots.py
```

The problem is that this is only conditionally included, since the Makefile.am is only conditionally included.  As a result, it is NOT included in a distribution.    To get around this, we need to make sure that EXTRA_DIST is always included (not only conditionally).  As a work-around, these can be included AFTER the conditional compile in Makefile.apps

**Comment by cburstedde** [comment]
A fix would be to always include all Makefile.ams, and use the conditional checks inside each Makefile.am.
