### ISSUE TITLE
Issues with stdin not returning blocking status.  

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#147]
I often get the following error from the bash command line (Ubuntu 18.04.5 LTS) : 

```
(bash) ~ % cat > foo
cat: -: Resource temporarily unavailable
```

when calling a bash command that reads the command line.    Other commands that return this error include "rm", "cp" and so on.  

I tracked down the issue to something in ForestClaw not returning to the terminal in "blocking" status.  I suspect that something is going wrong with the way I have set up option registration.  

The error can be reproduced in the "dummy" example.   Compile the example, and then run in parallel : 

```
(bash) $ mpirun -n 4 dummy
```

Then try something like : 

```
(bash) $ cat > foo
```

This should return with the error above.    This error doesn't happen when running in serial. 

Here is a program that can be used to check the block status of the console : 

```
// check_stdin.c
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

int main() {
    int flags;
    if ((flags = fcntl(STDIN_FILENO, F_GETFL, 0)) < 0) {
        printf("Error calling fcntl in %s: %s\n", __FUNCTION__, strerror(errno));
    }
    if (0 != (flags & (O_NONBLOCK))) {
        printf("Warning, STDIN in nonblock mode\n");
    }
    return EXIT_SUCCESS;
}
```

and this can be used to set the status : 

```
// set_blocking_status.c
#include <stdio.h>
#include <fcntl.h>
#include <stdlib.h>
#include <sys/ioctl.h>

int main(int argc, char **argv)
{

   int flags = fcntl(0, F_GETFL, 0);
   printf("stdin was formerly %sblocking\n", (flags & O_NONBLOCK) ? "non" : "");

   int nb = argc < 2 ? 0 : atoi(argv[1]);
   ioctl(0, FIONBIO, &nb);

   flags = fcntl(0, F_GETFL, 0);
   printf("stdin is now %sblocking\n", (flags & O_NONBLOCK) ? "non" : "");
}
```

Setting the status to `1` will reset the console.  

```
 (bash) $ set_blocking_status 1
```

I have never encountered this error in OSX.  

Here are a few links on this issue : 

https://unix.stackexchange.com/questions/437409/problems-caused-by-stdin-set-to-non-blocking-mode

https://stackoverflow.com/questions/19895185/bash-shell-read-error-0-resource-temporarily-unavailable

Or, Google *bash blocking stdin* for many more links to this issue.

**Comment by cburstedde** [comment]
This sounds more like an error of the MPI runtime. Have you tried to compile mpich?
