### ISSUE TITLE
Test fail on current develop branch

### ISSUE THREAD

**Issue by cburstedde** [ForestClaw/forestclaw#203]
I checked out the current develop at c18114739420dbabbe64215d7a978e1fcb305c08 and did `git submodule update`.

I configured `--enable-mpi --enable-debug --enable-clawpack CFLAGS="-Wall -O0 -g"` and get on `make check`:

    FAIL: applications/clawpack/acoustics/2d/radial/regressions.sh
    FAIL: applications/clawpack/euler/2d/quadrants/regressions.sh
    FAIL: applications/clawpack/shallow/2d/bump/regressions.sh

**Comment by donnaaboise** [comment]
I am assuming the error is a segfault of some sort?

**Comment by cburstedde** [comment]
I can look at the testsuite.log, let me check.

**Comment by cburstedde** [comment]
We've added LIBS=-lgfortran to the configure line and used the latest develop of forestclaw. It works fine now!
