### ISSUE TITLE
Error in test case "fclaw_global_new default options"

### ISSUE THREAD

**Issue by hannesbrandt** [ForestClaw/forestclaw#341]
When configuring the latest develop-3d branch with --enable-debug on Linux I run into the following error when calling make check-TESTS
```
FAIL: src/forestclaw.TEST --test-case="fclaw_global_new default options"
```
The corresponding error message is
```
 ../forestclaw/src/fclaw_global.h.TEST.cpp:62: ERROR: CHECK( glob->user == nullptr ) is NOT correct!
  values: CHECK( 0xffffffffffffffff == nullptr ) 
```

**Comment by scottaiton** [comment]
`glob->user` isn't being initialized in `fclaw_global_new()` 🤦. I'll have a fix soon.

**Comment by hannesbrandt** [comment]
Everything runs through cleanly now, thanks!
