### ISSUE TITLE
Doxygen?

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#64]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

Get a start on documentation?  

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/64

**Comment by cburstedde** [comment]
We have done a lot of work on the libsc doxygen system, and some on p4est. With upcoming merges, the structure there may be used as guidelines to expand on the ForestClaw documentation.

Note that we rely on several configure-time variable such as @PACKAGE_NAME@. These are automatically replaced by autoconf. With CMake, we need an additional filter step to substitute all of these in Doxyfile.in to create Doxyfile.
