### ISSUE TITLE
Reporting errors across MPI processes

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#76]
Originally reported by: **Carsten Burstedde (Bitbucket: [cburstedde](https://bitbucket.org/cburstedde), GitHub: [cburstedde](https://github.com/cburstedde))**

----------------------------------------

In a parallel application, some errors necessarily occur on all processors (command line parsing), others don't (inconsistency in some algorithm, serial file writing). When the program is to be aborted anyway, such as on file input and MPI errors, there is no need to resolve the situation. What would be nice though is to report the error up the call trace whenever possible, which might produce something like:

    file_open: could not open foo
    reading input data: could not process foo data file
    program setup: data loading unsuccessful

Thus there should be a stack and a way to synchronize errors in parallel. Will think about an addition to libsc to do this.

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/76

**Comment by cburstedde** [comment]
I've been thinking about such a stack framework, too. Very nice concept. Would fit well into libsc.

In the meantime, if just checking the flag is enough, I'd suggest an sc_MPI_Allgather with sc_MPI_LAND or sc_MPI_LOR. Code like this is in p4est_communication.c; see p4est_comm_sync_flag.
