### ISSUE TITLE
Store fclaw_app_t ?

### ISSUE THREAD

**Issue by donnaaboise** [ForestClaw/forestclaw#79]
Originally reported by: **Donna Calhoun (Bitbucket: [donnaaboise](https://bitbucket.org/donnaaboise), GitHub: [donnaaboise](https://github.com/donnaaboise))**

----------------------------------------

Where will the 'fclaw_app_t' ultimately be stored?   the easiest thing to do at the point is to just make it a member of domain.    This way, all user defined options can be easily available from just about anywhere in the app. 

----------------------------------------
- Bitbucket: https://bitbucket.org/donnaaboise/forestclaw/issue/79

**Comment by cburstedde** [comment]
What I would want to preserve is that domain does not depend on any other forestclaw code.
Domain does not need to be a toplevel container, though. If attributes or global data are stored in other objects, such as app (of which there is only one through the life of the program), that's fine with me.

**Comment by donnaaboise** [comment]
everything is now stored in `fclaw2d_global_t`.
